package com.jennifertellez.firstgen.model.enums;

public enum CulturalIdentity {
    MEXICAN_OR_CHICANO,
    PUERTO_RICAN,
    CUBAN,
    CENTRAL_AMERICAN,
    SOUTH_AMERICAN,
    OTHER_HISPANIC_OR_LATINO,
    WHITE_OR_CAUCASIAN,
    BLACK_OR_AFRICAN_AMERICAN,
    EAST_ASIAN,
    SOUTHEAST_ASIAN,
    SOUTH_ASIAN,
    MIDDLE_EASTERN_OR_NORTH_AFRICAN,
    NATIVE_AMERICAN_OR_ALASKA_NATIVE,
    NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER,
    MULTIRACIAL,
    PREFER_NOT_TO_SAY,
    OTHER
}
